// Code generated by "stringer -type=CrossOrigin"; DO NOT EDIT.

package script

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DefaultCrossOrigin-0]
	_ = x[Anonymous-1]
	_ = x[UseCredentials-2]
}

const _CrossOrigin_name = "DefaultCrossOriginAnonymousUseCredentials"

var _CrossOrigin_index = [...]uint8{0, 18, 27, 41}

func (i CrossOrigin) String() string {
	if i < 0 || i >= CrossOrigin(len(_CrossOrigin_index)-1) {
		return "CrossOrigin(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CrossOrigin_name[_CrossOrigin_index[i]:_CrossOrigin_index[i+1]]
}
