// Code generated by "stringer -type=ReferrerPolicy"; DO NOT EDIT.

package script

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[NoReferrer-1]
	_ = x[NoReferrerWhenDowngrade-2]
	_ = x[Origin-3]
	_ = x[OriginWhenCrossOrigin-4]
	_ = x[SameOrigin-5]
	_ = x[StrictOrigin-6]
	_ = x[StrictOriginWhenCrossOrigin-7]
	_ = x[UnsafeURL-8]
}

const _ReferrerPolicy_name = "NoneNoReferrerNoReferrerWhenDowngradeOriginOriginWhenCrossOriginSameOriginStrictOriginStrictOriginWhenCrossOriginUnsafeURL"

var _ReferrerPolicy_index = [...]uint8{0, 4, 14, 37, 43, 64, 74, 86, 113, 122}

func (i ReferrerPolicy) String() string {
	if i < 0 || i >= ReferrerPolicy(len(_ReferrerPolicy_index)-1) {
		return "ReferrerPolicy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReferrerPolicy_name[_ReferrerPolicy_index[i]:_ReferrerPolicy_index[i+1]]
}
